pluginGroup = com.github.btakita.agentdoc
pluginName = agent-doc-jetbrains
pluginVersion = 0.2.522
pluginSourceDigest = 32b992c4079b4b15664a31b1cad3207bf10ae7f57b50ebd776ca11ca608d36eb
platformVersion = 2026.2

kotlin.stdlib.default.dependency = false
org.gradle.configuration-cache = false
org.gradle.caching = true
org.gradle.jvmargs = -Xmx4g -XX:MaxMetaspaceSize=1g
pluginReleaseVersion = 0.35.483
