pluginGroup = com.github.btakita.agentdoc
pluginName = agent-doc-jetbrains
pluginVersion = 0.2.520
pluginSourceDigest = db52b61e191f4518b69f696b7bfb223e1214551bd3459c0e02f40d36d968db0c
platformVersion = 2026.2

kotlin.stdlib.default.dependency = false
org.gradle.configuration-cache = false
org.gradle.caching = true
org.gradle.jvmargs = -Xmx4g -XX:MaxMetaspaceSize=1g
pluginReleaseVersion = 0.35.483
