pluginGroup = com.github.btakita.agentdoc
pluginName = agent-doc-jetbrains
pluginVersion = 0.2.511
pluginSourceDigest = fc63adf298491db6709cc7f16f10bf812b5c3b68d6c1f9a421da18406620a615
platformVersion = 2026.2

kotlin.stdlib.default.dependency = false
org.gradle.configuration-cache = false
org.gradle.caching = true
org.gradle.jvmargs = -Xmx4g -XX:MaxMetaspaceSize=1g
pluginReleaseVersion = 0.35.480
