[package]
name = "agent-doc-element-queue"
version = "0.35.95"
edition = "2024"
description = "Queue element descriptor for agent-doc"
license = "MIT"
repository = "https://github.com/btakita/agent-doc"
publish = false

[lib]
name = "agent_doc_element_queue"

[dependencies]
agent-doc-state-scope = { path = "../agent-doc-state-scope", version = "0.35.95" }
agent-doc-element = { path = "../agent-doc-element", version = "0.35.95" }
lazily = { version = "0.53.0", features = ["thread-safe"] }
serde = { version = "1", features = ["derive"] }
